# Generated by Django 5.2.3 on 2025-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"verbose_name": "Метка", "verbose_name_plural": "Метки"},
        ),
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Имя"),
        ),
    ]
